#include "Combat/StatusDef.h"

namespace Dark::Combat
{
    namespace
    {
        constexpr StatusDef kStatusCatalog[] = {
            {
                .id                   = StatusId::Stun,
                .name                 = "Stun",
                .damageType           = DamageType::True,
                .stack                = StatusStackRule::RefreshLonger,
                .maxStacks            = 1,
                .hardCc               = true,
                .ccCategory           = CcCategory::Stun,
                .defaultDuration      = 1.2f,
                .defaultMagnitude     = 1.f,
                .tickDamage           = 0.f,
                .tickInterval         = 1.f,
                .tickScalesWithStacks = false,
                .particle             = StatusParticlePreset::StunStars,
                .particleLoop         = true,
                .applyCue             = "impact",
                .loopCue              = "",
                .expireCue            = "",
                .audioPriority        = 0,
                .animBool             = "stunned",
                .animTrigger          = "",
            },
            {
                .id                   = StatusId::Root,
                .name                 = "Root",
                .damageType           = DamageType::True,
                .stack                = StatusStackRule::RefreshLonger,
                .maxStacks            = 1,
                .hardCc               = false,
                .ccCategory           = CcCategory::Root,
                .defaultDuration      = 0.8f,
                .defaultMagnitude     = 1.f,
                .tickDamage           = 0.f,
                .tickInterval         = 1.f,
                .tickScalesWithStacks = false,
                .particle             = StatusParticlePreset::None,
                .particleLoop         = true,
                .applyCue             = "",
                .loopCue              = "",
                .expireCue            = "",
                .audioPriority        = 0,
                .animBool             = "",
                .animTrigger          = "",
            },
            {
                .id                   = StatusId::Fear,
                .name                 = "Fear",
                .damageType           = DamageType::True,
                .stack                = StatusStackRule::RefreshLonger,
                .maxStacks            = 1,
                .hardCc               = false,
                .ccCategory           = CcCategory::Fear,
                .defaultDuration      = 1.0f,
                .defaultMagnitude     = 1.f,
                .tickDamage           = 0.f,
                .tickInterval         = 1.f,
                .tickScalesWithStacks = false,
                .particle             = StatusParticlePreset::None,
                .particleLoop         = true,
                .applyCue             = "",
                .loopCue              = "",
                .expireCue            = "",
                .audioPriority        = 0,
                .animBool             = "",
                .animTrigger          = "",
            },
            {
                .id                   = StatusId::Knockdown,
                .name                 = "Knockdown",
                .damageType           = DamageType::True,
                .stack                = StatusStackRule::RefreshLonger,
                .maxStacks            = 1,
                .hardCc               = true,
                .ccCategory           = CcCategory::Knockdown,
                .defaultDuration      = 1.4f,
                .defaultMagnitude     = 1.f,
                .tickDamage           = 0.f,
                .tickInterval         = 1.f,
                .tickScalesWithStacks = false,
                .particle             = StatusParticlePreset::None,
                .particleLoop         = true,
                .applyCue             = "",
                .loopCue              = "",
                .expireCue            = "",
                .audioPriority        = 0,
                .animBool             = "",
                .animTrigger          = "",
            },
            {
                .id                   = StatusId::Poison,
                .name                 = "Poison",
                .damageType           = DamageType::Poison,
                .stack                = StatusStackRule::RefreshDurationMaxMag,
                .maxStacks            = 1,
                .hardCc               = false,
                .ccCategory           = CcCategory::Count,
                .defaultDuration      = 8.f,
                .defaultMagnitude     = 1.f,
                .tickDamage           = 4.f,
                .tickInterval         = 1.f,
                .tickScalesWithStacks = false,
                .particle             = StatusParticlePreset::PoisonCloud,
                .particleLoop         = true,
                .applyCue             = "fire",
                .loopCue              = "",
                .expireCue            = "",
                .audioPriority        = 0,
                .animBool             = "poisoned",
                .animTrigger          = "",
            },
            {
                .id                   = StatusId::Bleed,
                .name                 = "Bleed",
                .damageType           = DamageType::Slash,
                .stack                = StatusStackRule::RefreshDurationMaxMag,
                .maxStacks            = 1,
                .hardCc               = false,
                .ccCategory           = CcCategory::Count,
                .defaultDuration      = 6.f,
                .defaultMagnitude     = 1.f,
                .tickDamage           = 2.f,
                .tickInterval         = 1.f,
                .tickScalesWithStacks = false,
                .particle             = StatusParticlePreset::BleedDrip,
                .particleLoop         = true,
                .applyCue             = "impact",
                .loopCue              = "",
                .expireCue            = "",
                .audioPriority        = 0,
                .animBool             = "bleeding",
                .animTrigger          = "",
            },
            {
                .id                   = StatusId::Ignite,
                .name                 = "Ignite",
                .damageType           = DamageType::Fire,
                .stack                = StatusStackRule::RefreshDurationMaxMag,
                .maxStacks            = 1,
                .hardCc               = false,
                .ccCategory           = CcCategory::Count,
                .defaultDuration      = 6.f,
                .defaultMagnitude     = 1.f,
                .tickDamage           = 2.f,
                .tickInterval         = 1.f,
                .tickScalesWithStacks = false,
                .particle             = StatusParticlePreset::IgniteFlames,
                .particleLoop         = true,
                .applyCue             = "fire",
                .loopCue              = "",
                .expireCue            = "",
                .audioPriority        = 0,
                .animBool             = "ignited",
                .animTrigger          = "",
            },
            {
                .id                   = StatusId::Chill,
                .name                 = "Chill",
                .damageType           = DamageType::Frost,
                .stack                = StatusStackRule::RefreshDurationMaxMag,
                .maxStacks            = 1,
                .hardCc               = false,
                .ccCategory           = CcCategory::Count,
                .defaultDuration      = 6.f,
                .defaultMagnitude     = 0.5f,
                .tickDamage           = 0.f,
                .tickInterval         = 1.f,
                .tickScalesWithStacks = false,
                .particle             = StatusParticlePreset::ChillMist,
                .particleLoop         = true,
                .applyCue             = "impact",
                .loopCue              = "",
                .expireCue            = "",
                .audioPriority        = 0,
                .animBool             = "chilled",
                .animTrigger          = "",
            },
            {
                .id                   = StatusId::Shock,
                .name                 = "Shock",
                .damageType           = DamageType::Lightning,
                .stack                = StatusStackRule::RefreshDurationMaxMag,
                .maxStacks            = 1,
                .hardCc               = false,
                .ccCategory           = CcCategory::Count,
                .defaultDuration      = 3.f,
                .defaultMagnitude     = 1.f,
                .tickDamage           = 0.f,
                .tickInterval         = 1.f,
                .tickScalesWithStacks = false,
                .particle             = StatusParticlePreset::ShockSparks,
                .particleLoop         = true,
                .applyCue             = "impact",
                .loopCue              = "",
                .expireCue            = "",
                .audioPriority        = 0,
                .animBool             = "shocked",
                .animTrigger          = "",
            },
        };

        static_assert(sizeof(kStatusCatalog) / sizeof(kStatusCatalog[0]) == static_cast<size_t>(kStatusIdCount) - 1u);
    } // namespace

    const StatusDef* statusDef(StatusId id)
    {
        const int i = static_cast<int>(id);
        if (i <= 0 || i >= kStatusIdCount)
            return nullptr;
        const StatusDef& row = kStatusCatalog[i - 1];
        if (row.id != id)
            return nullptr;
        return &row;
    }

} // namespace Dark::Combat
